name: ChineseName
version: '${project.version}'
main: cn.paper_card.chinese_name.ThePlugin
api-version: '1.20'
author: Paper99
folia-supported: true

depend:
  - Database

softdepend:
  - PlayerCoins

commands:
  ch-name:
    permission: ch-name.command

permissions:
  ch-name.command:
    default: true
